// action types
export const MESSAGE_SEND = 'MESSAGE_SEND'
export const MESSAGE_CONFIRMATION = 'MESSAGE_CONFIRMATION'
export const MESSAGE_RESET = 'MESSAGE_RESET'

export const REQUEST_START = 'REQUEST_START'
export const REQUEST_END = 'REQUEST_END'
